test: ActionsTests improvements
FlaUI/FlaUI.WebDriver pull request #4
Opened 2024-03-31 04:00 UTC by Dor-bl

Added SetUp and TearDown Attributes
Moved the active element text one step earlier for easier debugging

2024-04-02 10:54 UTC, aristotelos requested changes
Added a few comments, thanks for the contribution!

2024-04-02 10:54 UTC, aristotelos commented on src/FlaUI.WebDriver.UITests/ActionsTest.cs
> +            driver?.Quit();
```suggestion
            driver?.Dispose();
```

2024-04-02 10:54 UTC, aristotelos commented on src/FlaUI.WebDriver.UITests/ActionsTest.cs
> +        private RemoteWebDriver driver;
I'd like to comply with https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md, so this should be:
```suggestion
        private RemoteWebDriver _driver;
```

2024-04-08 06:27 UTC, aristotelos reviewed
The use of `_driver` on line 12 and `driver` on line 18 won't build...

2024-04-08 06:36 UTC, Dor-bl commented
> The use of `_driver` on line 12 and `driver` on line 18 won't build...

Right..wasn't paying attention

2024-04-09 20:10 UTC, Dor-bl commented
@aristotelos fixed

2024-04-10 05:35 UTC, aristotelos approved these changes

2024-04-10 05:35 UTC, merged