works around issues with the webdriver spec
FlaUI/FlaUI.WebDriver pull request #92
Opened 2024-09-27 01:40 UTC by bmarroquin

* Disables the IntlBackslash key is covered by the non-int one already
* makes the shifted version of `.` be `>`
* Adds tests to test all type-able English keys

2024-09-27 06:56 UTC, aristotelos requested changes
Looks great in general, thank you for your contribution! Added some minor comments

2024-09-27 06:56 UTC, aristotelos commented on src/FlaUI.WebDriver/Keys.cs
> +        //{ '<', "IntlBackslash" },
Remove commented code

2024-09-27 06:56 UTC, aristotelos commented on src/FlaUI.WebDriver/Keys.cs
> +        //{ '>', "IntlBackslash" },
Remove commented code

2024-09-27 06:56 UTC, aristotelos commented on src/FlaUI.WebDriver.UITests/ElementTests.cs
> +        public void SendKeys_Qwerty()
The test method names should follow the pattern `command - state under test - expected behavior`.
```suggestion
        public void SendKeys_UpperAndLowercaseLetters_EntersIdenticalText()
```

2024-09-27 06:56 UTC, aristotelos commented on src/FlaUI.WebDriver.UITests/ElementTests.cs
> +        public void SendKeys_NumberRow()
```suggestion
        public void SendKeys_NumbersAndShiftedNumbers_EntersIdenticalText()
```

2024-09-27 06:56 UTC, aristotelos commented on src/FlaUI.WebDriver.UITests/ElementTests.cs
> +        public void SendKeys_Others()
```suggestion
        public void SendKeys_OtherCharacters_EntersIdenticalText()
```

2024-09-28 11:55 UTC, aristotelos approved these changes

2024-09-30 05:44 UTC, merged

2026-06-06 03:49 UTC, deubertviniciussouza-crypto reviewed
Karatê bastante fruta não vai fugitivo

2026-06-06 03:49 UTC, deubertviniciussouza-crypto commented
bmarroquin:fix-keys